"""
Django settings for Sec_Tools project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'o=g9x)0%m*2xd9+=-@f38yeofw6_&u0#w=%d+@o$-(z+32+a0k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, "static")
# ]
STATIC_ROOT = os.path.join(BASE_DIR, "static")

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'password_reset',
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'webscan.apps.WebscanConfig',
    'login.apps.LoginConfig',
    'webscan_backend.apps.WebscanBackendConfig',
    'dirscan.apps.DirscanConfig',
    'vulnscan.apps.VulnscanConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Sec_Tools.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'Sec_Tools.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
LOGIN_URL = '/login/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')
MEDIA_URL = '/media/'

#SimpleUi后台设置
#SIMPLEUI_LOGO = 'https://jwt1399.top//medias/logo.png' #登录页和后台logo
SIMPLEUI_LOGO = 'media/icons/favicon.ico' #登录页和后台logo
SIMPLEUI_ANALYSIS = False #是否向SimpleUi收集分析信息
SIMPLEUI_LOADING = False #是否打开Loading遮罩层
SIMPLEUI_LOGIN_PARTICLES = True #登录页粒子动画
SIMPLEUI_STATIC_OFFLINE = True #是否以脱机模式加载静态资源，为True的时候将默认从本地读取所有资源，即使没有联网一样可以。适合内网项目，不填该项或者为False的时候，默认从第三方的cdn获取
SIMPLEUI_HOME_INFO = False #是否打开SimpleUi服务器信息
SIMPLEUI_DEFAULT_THEME = 'simpleui.css' #默认主题 https://simpleui.88cto.com/docs/simpleui/QUICK.html#%E9%BB%98%E8%AE%A4%E4%B8%BB%E9%A2%98
SIMPLEUI_HOME_QUICK = True #后台页面是否显示最近动作


# AWVS URL和API key  服务器版本
API_URL = 'https://your:3443'
API_KEY = '***your**'

# 重设密码功能邮箱配置
EMAIL_HOST = '***your**'
EMAIL_PORT = 25                             # 发件箱的smtp服务器端口
EMAIL_HOST_USER = '***your**'       # 你的邮箱账号
EMAIL_HOST_PASSWORD ="***your**"     # 邮箱授权码
EMAIL_USE_TLS = True                        # 这里必须是 True，否则发送不成功
EMAIL_FROM = '***your**'            # 你的邮箱账号
DEFAULT_FROM_EMAIL = '***your**'    # 你的邮箱账号

#自定义后台菜单
SIMPLEUI_CONFIG = {
    'system_keep': False,  #去除系统模块
    'menus': [{
        'name': '导航管理',
        'icon': 'fas fa-book-open',
        'models': [{
                'name': '分类',
                'icon': 'fas fa-list',
                'url': '/admin/webscan/category/'
            },{
                'name': '条目',
                'icon': 'fas fa-tags',
                'url': '/admin/webscan/item/'
            }]
    }, {
        'name': '指纹组件',
        'icon': 'fas fa-fingerprint',
        'models': [{
            'name': '分类',
            'icon': 'fas fa-list',
            'url': '/admin/webscan/fpcategory/'
        }, {
            'name': '条目',
            'icon': 'fas fa-tags',
            'url': '/admin/webscan/fingerprint/'
        }]
    }, {
        'name': '端口列表',
        'icon': 'fab fa-battle-net',
        'url': '/admin/webscan/portlist/'
    }, {
        'name': '中间件扫描',
        'icon': 'fab fa-battle-net',
        'url': '/admin/vulnscan/middleware_vuln/'
    }, {
        'app': 'auth',
        'name': '用户和授权',
        'icon': 'fas fa-user-shield',
        'models': [{
            'name': '用户',
            'icon': 'fa fa-user',
            'url': 'auth/user/'
        },{
            'name': '权限组',
            'icon': 'fas fa-users-cog',
            'url': 'auth/group/'
        }]
    }, {
        'name': '网页预览',
        'icon': 'fas fa-paper-plane',
        'models': [{
            'name': 'Sec-Tools',
            'url': 'http://127.0.0.1:8002/',
            'icon': 'fas fa-user-secret'
        }, {
            'name': '简简',
            'url': 'https://jwt1399.top',
            'icon': 'fas fa-crown'
        }]
    }]
}

