import random
def test():
    test = [
        {"domain": "www.microsoft.com",'title': None},
        {"domain": "beta.update.microsoft.com",'title': None},
        {"domain": "forums.microsoft.com.mk",'title': None},
        {"domain": "dspopensearchstg.search.microsoft.com",'title': None},
        {"domain": "www.black-moka.eu",'title': None},
        {"domain": "guoyidan.cn",'title': None},
        {"domain": "www2.peakesdrive.co.uk",'title': None},
        {"domain": "www.guoyidan.cn",'title': None},
        {"domain": "dpcenterppe.microsoft.com",'title': None},
        {"domain": "www.thecedargroup.com",'title': None},
        {"domain": "e13678.dscb.akamaiedge.net.0.1.cn.akamaiedge.net",'title': None},
        {"domain": "www.tourradar.sucks",'title': None},
        {"domain": "privacy.microsoft.com.edgekey.net",'title': None},
        {"domain": "sevillegwus.microsoft.com",'title': None},
        {"domain": "www.noeapi.com",'title': None},
        {"domain": "partnerppe.microsoft.com",'title': None},
        {"domain": "us.tip2.powerquery.microsoft.com",'title': None},
        {"domain": "l1.trafficmanager.net",'title': None},
        {"domain": "evaandoliver.xyz",'title': None},
        {"domain": "go.microsoft.co.uk",'title': None},
        {"domain": "linux.rtcomm.ru",'title': None},
        {"domain": "e13678.dspb.akamaiedge.net.0.1.cn.akamaiedge.net",'title': None},
        {"domain": "polaris-ppe.microsoft.com",'title': None},
        {"domain": "ms.helifan.net",'title': None},
        {"domain": "woodyhu.com",'title': None},
        {"domain": "wwwqa.microsoft.com",'title': None},
        {"domain": "test.penneycomputer.com",'title': None},
        {"domain": "www.akshaylive.tk",'title': None},
        {"domain": "winatp-gw.microsoft.com",'title': None},
        {"domain": "ms.softcell.co.in",'title': None},
        {"domain": "alchemy-api-acc.microsoft.com",'title': None}
    ]
    _text = [{"domain": "home.aifengjie.com",'title': None},
                 {"domain": "q9jexc.cn",'title': None},
                 {"domain": "650sf.com",'title': None},
                 {"domain": "www.72844912.xyz",'title': None},
                 {"domain": "www.aaam.store",'title': None},
                 {"domain": "www.badu.red",'title': None},
                 {"domain": "cctv5bo.com",'title': None},
                 {"domain": "msite.baidu.com",'title': None},
                 {"domain": "xiongzhang.baidu.com",'title': None},
                 {"domain": "home.aifengjie.com",'title': None},
                 {"domain": "q9jexc.cn",'title': None},
                 {"domain": "650sf.com",'title': None},
                 {"domain": "www.72844912.xyz",'title': None},
                 {"domain": "www.aaam.store",'title': None},
                 {"domain": "www.badu.red",'title': None},
                 {"domain": "mmm1.safa.yamiya8.com",'title': None},
                 {"domain": "www.suqianfangchan.com",'title': None},
                 {"domain": "transcoder.tradaquan.com",'title': None},
                 {"domain": "lyjjj88.com",'title': None},
                 {"domain": "1202.top",'title': None},
                 {"domain": "www.chuang555.com",'title': None},
                 {"domain": "www.dayima.us",'title': None},
                 {"domain": "www.dns5.com.cn",'title': None},
                 {"domain": "www.dns5.com.cn",'title': None},
                ]
    return _text
