# Generated by Django 3.1.4 on 2021-04-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Middleware_vuln',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('result', models.CharField(max_length=100, null=True)),
                ('CVE_id', models.CharField(max_length=100, null=True)),
                ('time', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
    ]
