# Generated by Django 3.1.4 on 2021-06-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnscan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='middleware_vuln',
            name='time',
            field=models.DateTimeField(max_length=100, null=True, unique=True),
        ),
    ]
