# Generated by Django 3.1.4 on 2021-06-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnscan', '0002_auto_20210620_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='middleware_vuln',
            name='time',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
