# Generated by Django 3.1.4 on 2021-02-28 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webscan', '0002_auto_20210103_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='FpCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='PortList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.BigIntegerField(verbose_name='端口号')),
                ('service', models.TextField(max_length=100, verbose_name='服务')),
                ('protocol', models.CharField(blank=True, default='未知', max_length=20, verbose_name='协议')),
                ('status', models.CharField(blank=True, default='未知', max_length=10, verbose_name='状态')),
            ],
            options={
                'verbose_name': '端口列表',
                'verbose_name_plural': '端口列表',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='sort',
            field=models.IntegerField(default=1, verbose_name='显示顺序'),
        ),
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.TextField(max_length=100, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img_width',
            field=models.IntegerField(default=45, verbose_name='图片宽度'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
        migrations.CreateModel(
            name='FingerPrint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='组件名称')),
                ('desc', models.CharField(max_length=200, verbose_name='组件描述')),
                ('icon', models.FileField(default='/icons/default.ico', upload_to='icons/', verbose_name='组件logo')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webscan.fpcategory', verbose_name='组件类别')),
            ],
            options={
                'verbose_name': '指纹组件',
                'verbose_name_plural': '指纹组件',
            },
        ),
    ]
